FROM mcr.microsoft.com/devcontainers/universal
FROM mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
# RUN mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
COPY ./startemulator.sh /tmp/startemulator.sh
#RUN chmod +x /tmp/startemulator.sh
#RUN ["/bin/bash", "/tmp/startemulator.sh"]
